services:
    backend:
        build:
            context: ./backend
        container_name: blog-backend-dev
        image: blog-backend-dev
        volumes:
            - ./backend:/app
        ports:
            - '8000:8000'
    frontend:
        build:
            context: ./frontend
        container_name: blog-frontend-dev
        image: blog-frontend-dev
        volumes:
            - ./frontend:/app:ro
            - /app/node_modules
        ports:
            - '5173:5173'
        depends_on:
            - backend
