services:
  backend:
    build:
      context: ./backend
    container_name: backend-dev
    image: backend-dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    container_name: frontend-dev
    image: frontend-dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend